services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: .
    ports:
      - "8761:8761"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  spring-network:
    external: true
