services:
  # User Service
  user-service:
    build:
      context: .
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_URI=${EUREKA_URI}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      mysql-user:
        condition: service_healthy
    networks:
      - spring-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${SERVER_PORT}/actuator/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # MySQL for User Service
  mysql-user:
    image: mysql:8.4
    container_name: mysql-user
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-user-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - spring-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  spring-network:
    external: true

volumes:
  mysql-user-data:
