spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: email-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: ${EMAIL_HOST:smtp.titan.email}
    port: ${EMAIL_PORT:465}
    username: ${USER_NAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: ${SERVER_PORT:8081}
